### ISSUE TITLE
Cf client does not acknowledge duplicate responses

### ISSUE THREAD

**Issue by Lanterm** [mkovatsc/Californium#66]
In coap-18, the tests BlockwiseClientSide and ObserveClientSide currently fail. The reason is that the Cf client does not send an ACK when it receives a response a second time (a duplicate). Consequently, the server sends the response again and again, and eventually gives up.

I propose the following fix in the class: ch.ethz.inf.vs.californium.network.Matcher in function receiveResponse(). Currently, the end of the function looks like this:
```
if (response.getType() != Type.ACK) {
  LOGGER.info("Response with unknown Token "+idByTok+": Rejecting "+response);
  // This is a totally unexpected response.
  EmptyMessage rst = EmptyMessage.newRST(response);
  sendEmptyMessage(exchange, rst);
}
// ignore response
return null;

```

The method <code>sendEmptyMessage(exchange, rst);</code> does NOT send the RST and is rather ineffective. I suggest to replace the four lines in the if-statement with the following small block token from an earlier version:
```
if (response.getType() != Type.ACK) {
  Exchange prev = deduplicator.find(idByMID);
  if (prev != null) { 
    response.setDuplicate(true);
    return prev;
  }
}
```
As a result, the ReliabilityLayer will send an ACK to the server. Both tests mentioned above will succeed.

**Comment by mkovatsc** [comment]
Fixed in https://github.com/eclipse/californium/pull/16
