### ISSUE TITLE
Sending POST request from different machine stop other machine requests

### ISSUE THREAD

**Issue by avishu2111** [mkovatsc/Californium#69]
I'm using Californium. I have Californium server and I'm sending data from different machines.
When I start sending data from another machine it stops sending data for all other machine.

How can I overcome this problem?

**Comment by Lanterm** [comment]
I don't quite follow. Which machine stops sending data? Btw. Californium has moved to the Eclipse Foundation (https://github.com/eclipse/californium). You may use an outdated version.

**Comment by mkovatsc** [comment]
Good point! Only now I noticed that these mails come from this repository...
We currently have the problem that Eclipse disabled the issues there. Compliance says we should use BugZilla. Best you join the mailing list at https://dev.eclipse.org/mailman/listinfo/cf-dev
